name: Tests

on:
  - push
  - pull_request

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: '--external-sources --source-path=./lib'
      with:
        ignore_names: "esh"
